# Generated by Django 2.0.4 on 2018-04-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pinax_images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('origin', models.DateTimeField(auto_now_add=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=70, null=True, verbose_name='caption')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pinax_images.ImageSet')),
            ],
        ),
    ]
