# Generated by Django 2.0.4 on 2018-04-10 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='listing',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='listing.Listing', verbose_name='listing'),
            preserve_default=False,
        ),
    ]
