# Generated by Django 2.0.4 on 2018-04-13 13:31

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_picture_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='image',
        ),
        migrations.AddField(
            model_name='picture',
            name='detail_image',
            field=versatileimagefield.fields.VersatileImageField(default=1, height_field='height', upload_to='images/detail_listing/', verbose_name='Detail Image', width_field='width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='picture',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI'),
        ),
        migrations.AddField(
            model_name='picture',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width'),
        ),
    ]
