# Generated by Django 2.0.4 on 2018-04-13 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_auto_20180413_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='listing.Listing', verbose_name='listing'),
        ),
    ]
