# Generated by Django 2.0.4 on 2018-04-10 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_images', '0001_initial'),
        ('account', '0004_auto_20170416_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='alt_phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='alternate phone'),
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='my bio'),
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinax_images.ImageSet'),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='phone'),
        ),
    ]
