# Generated by Django 2.0.4 on 2018-04-12 14:27

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180410_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='image',
        ),
        migrations.AddField(
            model_name='account',
            name='agent_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='images/agents/', verbose_name='Agent Image', width_field='width'),
        ),
        migrations.AddField(
            model_name='account',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='account',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI'),
        ),
        migrations.AddField(
            model_name='account',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width'),
        ),
    ]
