# Generated by Django 2.0.4 on 2018-04-12 14:38

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180412_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='agent_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field=150, null=True, upload_to='images/agents/', verbose_name='Agent Image', width_field=110),
        ),
    ]
