# Generated by Django 2.0.4 on 2018-04-12 14:39

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20180412_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='agent_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='images/agents/', verbose_name='Agent Image', width_field='width'),
        ),
    ]
