# Generated by Django 2.0.4 on 2018-04-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20180412_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fb',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='account',
            name='goog',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Google+'),
        ),
        migrations.AddField(
            model_name='account',
            name='insta',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='account',
            name='linkd',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='account',
            name='mtup',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Meetup'),
        ),
        migrations.AddField(
            model_name='account',
            name='pin',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Pintrest'),
        ),
        migrations.AddField(
            model_name='account',
            name='snap',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Snap Chat'),
        ),
        migrations.AddField(
            model_name='account',
            name='twit',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='account',
            name='utube',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='phone'),
        ),
    ]
