# Generated by Django 2.0.4 on 2018-04-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('origin', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='property name')),
                ('street', models.CharField(blank=True, max_length=150, verbose_name='street address')),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='street address')),
                ('state', models.CharField(blank=True, max_length=150, verbose_name='state')),
                ('zipcode', models.CharField(blank=True, max_length=15, verbose_name='zipcode')),
                ('desription', models.TextField(blank=True, max_length=4000, null=True, verbose_name='description')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('price', models.PositiveIntegerField(default=1, verbose_name='listing price')),
                ('bedrooms', models.DecimalField(decimal_places=1, default=1, max_digits=4, verbose_name='bedrooms')),
                ('bathrooms', models.DecimalField(decimal_places=1, default=1, max_digits=4, verbose_name='bathrooms')),
                ('square_feet', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='square feet')),
                ('acres', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='acres')),
                ('mls_number', models.PositiveIntegerField(default=1, verbose_name='MLS number')),
                ('built_in', models.PositiveSmallIntegerField(default=0, verbose_name='built in')),
            ],
        ),
    ]
