# Generated by Django 2.0.4 on 2018-04-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Listing'},
        ),
        migrations.AddField(
            model_name='listing',
            name='motivated',
            field=models.BooleanField(default=False, verbose_name='motivated seller'),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_reduced',
            field=models.BooleanField(default=False, verbose_name='price reduced'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, max_length=150, verbose_name='city'),
        ),
    ]
