# Generated by Django 2.0.4 on 2018-04-12 13:37

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20180412_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=1, height_field='height', upload_to='images/main_listing/', verbose_name='Main Image', width_field='width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width'),
        ),
    ]
