# Generated by Django 2.0.4 on 2018-04-12 13:38

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20180412_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='images/main_listing/', verbose_name='Main Image', width_field='width'),
        ),
    ]
