# Generated by Django 2.0.4 on 2018-04-12 13:46

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20180412_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI'),
        ),
    ]
