# Generated by Django 2.0.4 on 2018-04-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_listing_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.CharField(choices=[('NA', 'Not Applicable'), ('0', '0'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7+', '7+')], default='0', max_length=15, verbose_name='bathrooms'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.CharField(choices=[('NA', 'Not Applicable'), ('0', '0'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7+', '7+')], default='0', max_length=15, verbose_name='bedrooms'),
        ),
    ]
