# Generated by Django 2.0.4 on 2018-04-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_auto_20180412_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='county',
            field=models.CharField(blank=True, max_length=50, verbose_name='county'),
        ),
        migrations.AddField(
            model_name='listing',
            name='elementary_sch',
            field=models.CharField(blank=True, max_length=150, verbose_name='elementary school'),
        ),
        migrations.AddField(
            model_name='listing',
            name='high_sch',
            field=models.CharField(blank=True, max_length=150, verbose_name='high school'),
        ),
        migrations.AddField(
            model_name='listing',
            name='middle_sch',
            field=models.CharField(blank=True, max_length=150, verbose_name='middle school'),
        ),
        migrations.AddField(
            model_name='listing',
            name='school_district',
            field=models.CharField(blank=True, max_length=150, verbose_name='school district'),
        ),
    ]
