# Generated by Django 2.0.4 on 2018-04-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_auto_20180412_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='square_feet',
            field=models.PositiveIntegerField(default=1, verbose_name='square feet'),
        ),
    ]
