# Generated by Django 2.0.4 on 2018-04-13 14:49

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_auto_20180412_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(max_length=150, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='desription',
            field=models.TextField(default=1, max_length=4000, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='elementary_sch',
            field=models.CharField(max_length=150, verbose_name='elementary school'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='high_sch',
            field=models.CharField(max_length=150, verbose_name='high school'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=1, height_field='height', upload_to='images/main_listing/', verbose_name='Main Image', width_field='width'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='middle_sch',
            field=models.CharField(max_length=150, verbose_name='middle school'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(default=1, max_length=30, verbose_name='property name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='school_district',
            field=models.CharField(max_length=150, verbose_name='school district'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(max_length=150, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='street',
            field=models.CharField(max_length=150, verbose_name='street address'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='zipcode',
            field=models.CharField(max_length=15, verbose_name='zipcode'),
        ),
    ]
