# Generated by Django 2.0.4 on 2018-04-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_auto_20180413_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='county',
            field=models.CharField(max_length=50, verbose_name='county'),
        ),
    ]
