# Generated by Django 2.0.4 on 2018-04-14 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_auto_20180413_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='account.Account', verbose_name='valued agent'),
            preserve_default=False,
        ),
    ]
