# Generated by Django 2.0.4 on 2018-04-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pinax_images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=12, null=True, verbose_name='caption')),
                ('bio', models.TextField(blank=True, max_length=4000, null=True, verbose_name='company bio')),
                ('alert', models.TextField(blank=True, max_length=4000, null=True, verbose_name='company alert')),
                ('phone_number', models.CharField(blank=True, max_length=12, verbose_name='main phone')),
                ('alt_phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='second phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='company email address')),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinax_images.ImageSet')),
            ],
        ),
    ]
