# Generated by Django 2.0.4 on 2018-04-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='caption',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='caption'),
        ),
    ]
