# Generated by Django 2.0.4 on 2018-04-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_auto_20180411_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name': 'Site detail'},
        ),
    ]
