# Generated by Django 2.0.4 on 2018-04-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_auto_20180411_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
