# Generated by Django 2.0.4 on 2018-04-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0004_details_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='text_color',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('e3827b', 'Red')], default='Black', max_length=30, verbose_name='text color'),
        ),
    ]
