# Generated by Django 2.0.4 on 2018-04-13 00:46

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0006_auto_20180413_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='height', null=True, upload_to='images/site/', verbose_name='Site Image', width_field='width'),
        ),
    ]
